### ISSUE TITLE
Merging this repository?

### ISSUE THREAD

**Issue by jamen** [soundcove/ui#1]
Hello.  I would like to know the status on merging this repository.

You could preserve the commits by moving it to an archive of yours (like my [jamen-archive](https://github.com/jamen-archive) account).

This is the last thing to do until all the repositories are cleaned up, so I was checking in.

**Comment by vectrixdevelops** [comment]
Waiting on @dustindowell22 and I to finish making changes.

**Comment by dustindowell22** [comment]
i already have a branch on app-client with the changes, it could probably be merged, but it's still not finished

**Comment by whaaaley** [comment]
PR is waiting to be merged
